version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: DailyDietApiDatabase
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: daily_diet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local